### ISSUE TITLE
Allow built-in defaults to be used

### ISSUE THREAD

**Issue by InfernoZeus** [cristifalcas/puppet-journald#1]
Currently the only way to use the built-in defaults of journald is to declare all of the values in params.pp as `undef`. This works but is rather clunky. It would be nice if there was something like a `disable_defaults` parameter for the main class.

(You might be wondering why I'd prefer not to use the defaults in params.pp. It's just that I've seen too many modules where the defaults aren't maintained after updates to the upstream project.)

**Comment by cristifalcas** [comment]
I added a new parameter (enable_defaults) that should fix this

**Comment by InfernoZeus** [comment]
Awesome, very quick response! Thanks :)
