### ISSUE TITLE
missing dependencies on inifile

### ISSUE THREAD

**Issue by tgermain** [cristifalcas/puppet-journald#3]
Hi,

I might have missed something but the call to `create_ini_settings` ( https://github.com/cristifalcas/puppet-journald/blob/master/manifests/config.pp#L29) depends on the official module [inifile](https://forge.puppet.com/puppetlabs/inifile).

I can make a PR to add it as a dependency of this module in metadata.json. I don't know if puppet forge will pick it up automatically or if you need to make a new release.

**Comment by pulecp** [comment]
It was fixed in 8781b5955ab8d17449bdbc0084a7297ab75d1c5b. This issue can be closed.
